import { Camera, Car, Coffee, Home, Mountain, Tent } from 'lucide-react';

export const categories = [
    { label: 'Homestay', icon: Home },
    { label: 'Jeep Tour', icon: Car },
    { label: 'Camping', icon: Tent },
    { label: 'Wisata', icon: Mountain },
    { label: 'Kuliner', icon: Coffee },
    { label: 'Fotografi', icon: Camera },
];

export const listings = [
    {
        id: 1,
        title: 'Homestay Cahaya Sikunir',
        category: 'Homestay',
        location: 'Sembungan, Dieng',
        price: 350000,
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1723810742992-0e84241abcf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwd29vZGVuJTIwY2FiaW4lMjBpbnRlcmlvciUyMGhvbWVzdGF5fGVufDF8fHx8MTc3MDk3MTUxNHww&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Homestay nyaman dengan pemandangan sunrise terbaik di desa tertinggi Pulau Jawa.',
    },
    {
        id: 2,
        title: 'Jeep Adventure Kawah Sikidang',
        category: 'Jeep Tour',
        location: 'Dieng Kulon',
        price: 750000,
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1765519333785-892ba0e85e91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZyb2FkJTIwamVlcCUyMGFkdmVudHVyZSUyMG11ZGR5JTIwZm9yZXN0fGVufDF8fHx8MTc3MDk3MTUxNHww&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Paket wisata jeep keliling Kawah Sikidang dan Candi Arjuna. Maksimal 4 orang.',
    },
    {
        id: 3,
        title: 'Glamping Telaga Warna',
        category: 'Camping',
        location: 'Telaga Warna, Dieng',
        price: 500000,
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1715529023436-ad8c4a4f202e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbGFtcGluZyUyMHRlbnQlMjBuYXR1cmUlMjBmb3Jlc3R8ZW58MXx8fHwxNzcwODk3NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Rasakan sensasi menginap di tepi danau dengan fasilitas lengkap dan api unggun.',
    },
    {
        id: 4,
        title: 'Villa Puncak Dieng',
        category: 'Homestay',
        location: 'Dieng Wetan',
        price: 1200000,
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1644496629469-a0355eeac153?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxEaWVuZyUyMFBsYXRlYXUlMjBtb3VudGFpbnMlMjBsYW5kc2NhcGUlMjBtaXN0eXxlbnwxfHx8fDE3NzA5NzE1MTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Villa keluarga kapasitas besar dengan air panas dan dapur lengkap.',
    },
    {
        id: 5,
        title: 'Sunrise Jeep Trip Sikunir',
        category: 'Jeep Tour',
        location: 'Bukit Sikunir',
        price: 850000,
        rating: 5.0,
        image: 'https://images.unsplash.com/photo-1585308057198-67070eb477d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW5yaXNlJTIwbW91bnRhaW4lMjB2aWV3JTIwY2xvdWRzJTIwZ29sZGVuJTIwaG91cnxlbnwxfHx8fDE3NzA5NzE1MTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Berburu golden sunrise di Bukit Sikunir tanpa lelah mendaki, diantar jeep sampai pos 1.',
    },
    {
        id: 6,
        title: 'Kawah Sikidang Experience',
        category: 'Wisata',
        location: 'Kawah Sikidang',
        price: 25000,
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1729627271922-9e5e1cb81b2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2b2xjYW5pYyUyMGNyYXRlciUyMHN1bGZ1ciUyMHNtb2tlJTIwbGFuZHNjYXBlfGVufDF8fHx8MTc3MDk3MTUxNXww&ixlib=rb-4.1.0&q=80&w=1080',
        description: 'Tiket masuk wisata kawah aktif yang unik dan instagramable.',
    },
    {
        id: 7,
        title: 'Homestay Arjuna View',
        category: 'Homestay',
        location: 'Dieng Kulon',
        price: 400000,
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1080&q=80',
        description: 'Homestay dengan balkon langsung menghadap komplek Candi Arjuna.',
    },
    {
        id: 8,
        title: 'Dieng Plateau Jeep Explorer',
        category: 'Jeep Tour',
        location: 'Dieng Wetan',
        price: 900000,
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
        description: 'Tour jeep private keliling Telaga Warna, Batu Pandang, dan Kawah Sikidang.',
    },
    {
        id: 9,
        title: 'Camping Ground Batu Ratapan Angin',
        category: 'Camping',
        location: 'Batu Ratapan Angin',
        price: 150000,
        rating: 4.4,
        image: 'https://images.unsplash.com/photo-1504280390368-3979c5cfa1a7?auto=format&fit=crop&w=1080&q=80',
        description: 'Area camping dengan view Telaga Warna dan Telaga Pengilon.',
    },
    {
        id: 10,
        title: 'Villa Dieng Asri',
        category: 'Homestay',
        location: 'Sembungan, Dieng',
        price: 1000000,
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?auto=format&fit=crop&w=1080&q=80',
        description: 'Villa modern minimalis dengan kapasitas 10 orang dan fasilitas BBQ.',
    },
    {
        id: 11,
        title: 'Golden Sunrise Package',
        category: 'Jeep Tour',
        location: 'Bukit Sikunir',
        price: 800000,
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
        description: 'Paket jeep sunrise + dokumentasi foto profesional.',
    },
    {
        id: 12,
        title: 'Telaga Pengilon Tour',
        category: 'Wisata',
        location: 'Telaga Pengilon',
        price: 20000,
        rating: 4.3,
        image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
        description: 'Tiket masuk danau jernih dengan panorama pegunungan.',
    },
    {
        id: 13,
        title: 'Homestay Sikunir Indah',
        category: 'Homestay',
        location: 'Sembungan, Dieng',
        price: 375000,
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1080&q=80',
        description: 'Penginapan hangat dekat jalur pendakian Bukit Sikunir.',
    },
    {
        id: 14,
        title: 'Offroad Lava Tour Dieng',
        category: 'Jeep Tour',
        location: 'Kawah Sikidang',
        price: 950000,
        rating: 5.0,
        image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1080&q=80',
        description: 'Sensasi offroad melewati jalur ekstrim dan lautan pasir.',
    },
    {
        id: 15,
        title: 'Glamping Luxury Dieng',
        category: 'Camping',
        location: 'Telaga Warna, Dieng',
        price: 650000,
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1526779259212-756e8b4e5c8f?auto=format&fit=crop&w=1080&q=80',
        description: 'Glamping premium dengan kasur queen size dan kamar mandi dalam.',
    },
    {
        id: 16,
        title: 'Candi Arjuna Heritage Tour',
        category: 'Wisata',
        location: 'Komplek Candi Arjuna',
        price: 30000,
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1552084117-56a987666449?auto=format&fit=crop&w=1080&q=80',
        description: 'Wisata sejarah ke komplek candi tertua di Dieng.',
    },
    {
        id: 17,
        title: 'Homestay Dieng Family House',
        category: 'Homestay',
        location: 'Dieng Wetan',
        price: 550000,
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1080&q=80',
        description: 'Rumah 3 kamar cocok untuk keluarga besar.',
    },
    {
        id: 18,
        title: 'Jeep Midnight Tour Dieng',
        category: 'Jeep Tour',
        location: 'Dieng Plateau',
        price: 1000000,
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
        description: 'Tour malam melihat milky way dan sunrise sekaligus.',
    },
    {
        id: 19,
        title: 'Bukit Scooter Ride',
        category: 'Wisata',
        location: 'Batu Ratapan Angin',
        price: 50000,
        rating: 4.2,
        image: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=1080&q=80',
        description: 'Sewa scooter listrik untuk keliling area wisata.',
    },
    {
        id: 20,
        title: 'Backpacker Homestay Dieng',
        category: 'Homestay',
        location: 'Dieng Kulon',
        price: 250000,
        rating: 4.3,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1080&q=80',
        description: 'Homestay budget untuk traveler solo dan backpacker.',
    },
];
